name: Lint

on:
  push:
    paths:
      - "**.go"
      - go.mod
      - go.sum
  pull_request:
    paths:
      - "**.go"
      - go.mod
      - go.sum

jobs:

  lint:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: "1.16.x"

    - name: Check out code
      uses: actions/checkout@v2

    - name: Verify dependencies
      run: |
        go mod verify
        go mod download
    
    - name: Installing static code analysis tools
      run: ./scripts/ci-lint-install.sh

    - name: Run checks
      run: ./scripts/ci-lint.sh
